services:
  app:
    build: .
    container_name: app-escola
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: aluno
      DB_PASSWORD: aluno123
      DB_NAME: escola
    depends_on:
      - db
    restart: on-failure

  db:
    image: mysql:8.0
    container_name: db-escola
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: escola
      MYSQL_USER: aluno
      MYSQL_PASSWORD: aluno123
    volumes:
      - db_data:/var/lib/mysql
      - ../scripts/criar-tabelas.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  db_data: